controller_manager:
    ros__parameters:
      update_rate: 10  # Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      pid_controller_fl_wheel:
        type: pid_controller/PidController

joint_state_broadcaster:
  ros__parameters:
    joints:
      - FL_wheel
      - BL_wheel
      - BR_wheel
      - FR_wheel
      - FL_steering
      - BL_steering
      - BR_steering
      - FR_steering

pid_controller_fl_wheel:
  ros__parameters:

    dof_names:
      - FL_wheel

    command_interface: effort

    reference_and_state_interfaces: ["velocity"]

    FL_wheel: {"p": 0.5, "i": 2.5, "d": 0.0, "i_clamp_min": -20.0, "i_clamp_max": 20.0, "antiwindup": true, "feedforward_gain": 0.95}
