controller_manager:
    ros__parameters:
      update_rate: 100  # Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      forward_effort_controller:
        type: forward_command_controller/ForwardCommandController

joint_state_broadcaster:
  ros__parameters:
    joints:
      - FL_wheel
      - BL_wheel
      - BR_wheel
      - FR_wheel
      - FL_steering
      - BL_steering
      - BR_steering
      - FR_steering

forward_effort_controller:
  ros__parameters:
    joints:
      - FL_wheel
      - BL_wheel
      - BR_wheel
      - FR_wheel
      - FL_steering
      - BL_steering
      - BR_steering
      - FR_steering
    interface_name: effort
    

