controller_manager:
    ros__parameters:
      update_rate: 100  # Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      pid_controller_fl_wheel:
        type: pid_controller/PidController

joint_state_broadcaster:
  ros__parameters:
    joints:
      - FL_wheel
      - BL_wheel
      - BR_wheel
      - FR_wheel
      - FL_steering
      - BL_steering
      - BR_steering
      - FR_steering

pid_controller_fl_wheel:
  ros__parameters:

    dof_names:
      - FL_wheel

    command_interface: effort

    reference_and_state_interfaces:
      - velocity

    gains:
      wheel_joint:
        p: 10.0
        i: 0.0
        d: 0.0
        i_clamp_max: 0.0
        i_clamp_min: 0.0
        # optional feedforward gain
        feedforward_gain: 0.0

    # You may also limit output
    output_saturation: 1.5   # e.g. limit effort/current magnitude

    # (Optional) If you want to chain this with other controllers, enable chained mode
    chained: false
      